# Example services.yaml entry

# Service ID
asdf:
  # If the service accepts entity IDs, target allows the user to specify entities by
  # entity, device, or area. If `target` is specified, `entity_id` should not be
  # defined in the `fields` map. By default it shows only targets matching entities
  # from the same domain as the service, but if further customization is required,
  # target supports the entity, device, and area selectors
  # (https://www.home-assistant.io/docs/blueprint/selectors/). Entity selector
  # parameters will automatically be applied to device and area, and device selector
  # parameters will automatically be applied to area.
  target:
    entity:
      domain: hdk_irrigation_system
      # If not all entities from the service's domain support a service, entities
      # can be further filtered by the `supported_features` state attribute. An
      # entity will only be possible to select if it supports at least one of the
      # listed supported features.
      supported_features:
        - fan.FanEntityFeature.SET_SPEED
        # If a service requires more than one supported feature, the item should
        # be given as a list of required supported features. For example, if the
        # service requires both SET_SPEED and OSCILLATE it would be expressed like this
        - - fan.FanEntityFeature.SET_SPEED
          - fan.FanEntityFeature.OSCILLATE
  # Different fields that your service accepts
  fields:
    # Key of the field
    sleep_time:
      # Whether or not field is required (default = false)
      required: true
      # Advanced fields are only shown when the advanced mode is enabled for the user
      # (default = false)
      advanced: true
      # Example value that can be passed for this field
      duration:
      # example: "low"
      # # The default field value
      # default: "high"
      # # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control
      # # the input UI for this field
      # selector:
      #   select:
      #     translation_key: "fan_speed"
      #     options:
      #       - "off"
      #       - "low"
      #       - "medium"
            - "high"
start_one_zone:
  name: Start one Zone
  description: Starts the irrigation of one single zone.
  fields:
    entity_id:
      name: Zone
      description: Which zone to irrigate.
      example: "switch.schedule_abcdef"
      required: true
      selector:
        entity:
          integration: hdk_irrigation_system
          domain: time
    irrigation_duration:
      name: Durration
      example: '"12:00"'
      required: false
      selector:
        time:

start_one_cycle:
  name: Start one Cycle
  description: Starts the irrigation of one cycle.
  fields:
    entity_id:
      name: Zone
      description: Which cycle to irrigate.
      example: "switch.schedule_abcdef"
      required: true
      selector:
        entity:
          integration: hdk_irrigation_system
          domain: time
    irrigation_duration:
      name: Time Preset
      description: Time to wait befor starting irrigation.
      example: '"12:00"'
      required: false
      selector:
        time: